### ISSUE TITLE
rake db:seed でエラーになってデータ投入できない

### ISSUE THREAD

**Issue by masoo** [makitokezuka/symptom-interview#49]
```
$ rake db:seed
```
でエラーがでて、データ投入できない

~~~
Creating patients
Creating templates
Creating hospitals
Creating categorises
Creating interview_sheets
rake aborted!
ArgumentError: '0' is not a valid sex
/media/sf_symptom-interview/db/fixtures/development/interview_sheets.rb:4:in `block in <top (required)>'
/media/sf_symptom-interview/db/fixtures/development/interview_sheets.rb:3:in `<top (required)>'
/media/sf_symptom-interview/db/seeds.rb:7:in `block in <top (required)>'
/media/sf_symptom-interview/db/seeds.rb:3:in `each'
/media/sf_symptom-interview/db/seeds.rb:3:in `<top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
~~~

**Comment by makitokezuka** [comment]
master branchにてPRマージ済み。
